### ISSUE TITLE
we need a graphic designer

### ISSUE THREAD

**Issue by garnetluvcookie** [PigeonVideo/PigeonVideo.github.io#10]
I'm pretty good at UI design and stuff like that, I can do some but we'll need more people. I know a few people who are really good at UI stuff, should I ask them?

**Comment by LankyBox01** [comment]
Sure!

**Comment by garnetluvcookie** [comment]
ok, i'll get some people

**Comment by LankyBox01** [comment]
Perfect!

**Comment by LankyBox01** [comment]
The UI designers were code-alt and aboutDavid. But they still haven't started.. soo

**Comment by aboutDavid** [comment]
> The UI designers were code-alt and aboutDavid. But they still haven't started.. soo

Graphic designers and UI designers are two different things, and, we have lives to. We can't spend 100% of our time on this project because again, we have lives.

**Comment by garnetluvcookie** [comment]
> > The UI designers were code-alt and aboutDavid. But they still haven't started.. soo
> 
> Graphic designers and UI designers are two different things, and, we have lives to. We can't spend 100% of our time on this project because again, we have lives.

yess!

**Comment by LankyBox01** [comment]
> > The UI designers were code-alt and aboutDavid. But they still haven't started.. soo
> 
> Graphic designers and UI designers are two different things, and, we have lives to. We can't spend 100% of our time on this project because again, we have lives.

Imagine how this could help you in your "live".
After we get promotion, we set up a donation page, ads, etc.
And all the profit will go to.. i guess you

**Comment by garnetluvcookie** [comment]
> > > The UI designers were code-alt and aboutDavid. But they still haven't started.. soo
> > 
> > 
> > Graphic designers and UI designers are two different things, and, we have lives to. We can't spend 100% of our time on this project because again, we have lives.
> 
> Imagine how this could help you in your "live".
> After we get promotion, we set up a donation page, ads, etc.
> And all the profit will go to.. i guess you

well technically all of us because afaik unfair pay distribution is illegal... at least in my state.

**Comment by LankyBox01** [comment]
Ok, but we still didn't.. just leave it like that. No ads, no donate page.
