### ISSUE TITLE
Garnet..

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#11]
Could you make a long and detailed contract which explains that:
* Once you sign it, you will buy a domain for PigeonVideo
* You can't get a refund
* You can cancel the domain at any time
* You can cancel the contract, but still no refund
Thankyou

**Comment by garnetluvcookie** [comment]
i'll try, but you're better off using something else

**Comment by LankyBox01** [comment]
What does that mean?

**Comment by garnetluvcookie** [comment]
mmm is there a contract maker out there

**Comment by LankyBox01** [comment]
No, write it yourself

**Comment by garnetluvcookie** [comment]
i'll try

**Comment by LankyBox01** [comment]
Do it fast pliz

**Comment by garnetluvcookie** [comment]
i have school and just fyi i'm lest busy after 3 PM EST

**Comment by garnetluvcookie** [comment]
so in about 2 hours

**Comment by LankyBox01** [comment]
Kkkkkk just write one

**Comment by garnetluvcookie** [comment]
got it

**Comment by garnetluvcookie** [comment]
oh and also they can't legally pay us because not everyone on the team is of age (around 14-16 years old, varies by state or country) so we need a plan B

**Comment by aboutDavid** [comment]
I also live in EST. It is currently 2:11PM.

**Comment by LankyBox01** [comment]
We'll find people who can fund us

**Comment by aboutDavid** [comment]
> We'll find people who can fund us

No one will fund you until you make some progress.

**Comment by garnetluvcookie** [comment]
I've made a draft as a Google Form here: https://forms.gle/jwCxdxFVWXLmS1mu6

**Comment by aboutDavid** [comment]
I don't think you can use Google Forms for legal documents.

**Comment by garnetluvcookie** [comment]
> I don't think you can use Google Forms for legal documents.

I made a _draft_.

**Comment by LankyBox01** [comment]
I dnt think we need it anymore
