### ISSUE TITLE
solution to getting a domain

### ISSUE THREAD

**Issue by garnetluvcookie** [PigeonVideo/PigeonVideo.github.io#12]
i know someone with a free server, do you want me to get that server with the pigeonvideo.com domain and make us admins?

**Comment by garnetluvcookie** [comment]
also, i have a weebly account but that's useless here if we don't want user interaction and account creation on the site

**Comment by LankyBox01** [comment]
Pigeonvideo.com?
We could do pigeon.video but .com is WAYY cooler

**Comment by garnetluvcookie** [comment]
> Pigeonvideo.com?
> We could do pigeon.video but .com is WAYY cooler

I'll get in touch with the person. And I agree that .com is the coolest and has been since March 15, 1985.

**Comment by LankyBox01** [comment]
And who is this "someone"?

**Comment by themagiclavalamp** [comment]
@LankyBox01 do you hate me or something?

**Comment by LankyBox01** [comment]
@themagiclavalamp I DO NOT HATE YOU, just because i commented Just ONE word in all caps, doesn't mean i hate you! I just wanted to highlight some things up. I am not trying to be rude

**Comment by garnetluvcookie** [comment]
> And who is this "someone"?

Someone I know in real life.

**Comment by LankyBox01** [comment]
Oh, how didhe get dat fr33 $3rv3r?

**Comment by garnetluvcookie** [comment]
> Oh, how didhe get da fr33 $3rv3r?

Actually, _she_ can't give us the server at the time. Sorry :(

**Comment by LankyBox01** [comment]
Oh..
