### ISSUE TITLE
Places you could advertise

### ISSUE THREAD

**Issue by aboutDavid** [PigeonVideo/PigeonVideo.github.io#13]
- https://riverside.rocks/community (he said you could advertise there)
- support.glitch.com
- dev.to

**Comment by LankyBox01** [comment]
That's all? Please don't make useless issues

**Comment by aboutDavid** [comment]
I was adding more but my internet went out. Be paitent.

**Comment by LankyBox01** [comment]
No, we don't need that. And we CANT advertise on glitch
