### ISSUE TITLE
can u add me to the github org please

### ISSUE THREAD

**Issue by themagiclavalamp** [PigeonVideo/PigeonVideo.github.io#14]
hi, can you add me please?

**Comment by LankyBox01** [comment]
I already did.. like 4 times! YOU have to accept it, check your email and click "Accept". It's starting to annoy me

**Comment by garnetluvcookie** [comment]
As per LankyBox01, but I didn't send anything.

**Comment by themagiclavalamp** [comment]
you kind of need to chill, i didnt know where it was

**Comment by themagiclavalamp** [comment]
im new to github

**Comment by themagiclavalamp** [comment]
@LankyBox01 ur kind of mean

**Comment by LankyBox01** [comment]
I am not mean! What makes you think i am so "mean"?
I did not do anything wrong :(
