### ISSUE TITLE
Temporary Homepage Build

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#16]
Hey garnet, couldya make a temporary CSS homepage?
If you're not garnetluvcookie, just give out suggestions here.

**Comment by garnetluvcookie** [comment]
sure

**Comment by LankyBox01** [comment]
K, use divs and class (CSS)

**Comment by garnetluvcookie** [comment]
got it

**Comment by LankyBox01** [comment]
Apparently the CSS isn't working..

**Comment by garnetluvcookie** [comment]
yeah, it's odd.

**Comment by LankyBox01** [comment]
I'm pretty sure git doesn't work with backend.
We'll migrate to glitch now.

**Comment by EddiesTech** [comment]
Fixed your CSS
https://github.com/PigeonVideo/PigeonVideo.github.io/pull/20
