### ISSUE TITLE
PHYTON

### ISSUE THREAD

**Issue by anishanne** [PigeonVideo/PigeonVideo.github.io#17]
Erm. Whats PHYTON?

**Comment by garnetluvcookie** [comment]
bruh
you mean python, and it's a programming language

**Comment by LankyBox01** [comment]
Hi, please don't make unrelated posts. Thankyou

**Comment by aboutDavid** [comment]
@LankyBox01 I see what he means. You spelled Python wrong. I'll fix it!

**Comment by anishanne** [comment]
Fixed in #19

**Comment by LankyBox01** [comment]
Oh.. k thankyou
