### ISSUE TITLE
python coder here!

### ISSUE THREAD

**Issue by 17lwinn** [PigeonVideo/PigeonVideo.github.io#2]
Hello! I am a python dev who can use the main modules and flask.

I can try and sort out an upload site, and admin for managing uploads! Can I help?

**Comment by LankyBox01** [comment]
Yess ;)
You have been invited to the organization.
Please accept it

**Comment by aboutDavid** [comment]
@17lwinn, see Discord.

**Comment by aboutDavid** [comment]
Also, this issue seems to be resolved, so I'm closing this.
