### ISSUE TITLE
bug with site.html

### ISSUE THREAD

**Issue by garnetluvcookie** [PigeonVideo/PigeonVideo.github.io#21]
[On my site](https://github.com/garnetluvcookie/garnetluvcookie.github.io), site.html works fine with readme, but here it doesn't...? Can someone fix this?

**Comment by LankyBox01** [comment]
The readme eqs made fore the repo, not site. Please stop ding changes for this week

**Comment by LankyBox01** [comment]
And please revert all your changes NOW!

**Comment by LankyBox01** [comment]
Btw, readme is the main site if you don't use an index.html.
Please educate yourself about github repositories
