### ISSUE TITLE
Garnet!!

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#24]
Replace the curren README.md with this snapshot: https://glitch.com/edit/#!/pigeonvideo
Just click on markdown and copypaste it

**Comment by garnetluvcookie** [comment]
doing

**Comment by garnetluvcookie** [comment]
you have to give me write access

**Comment by garnetluvcookie** [comment]
i just realized that you're 7 hours ahead of me :/

**Comment by LankyBox01** [comment]
I can't give you acess - use pull requests so i know what you're do

**Comment by garnetluvcookie** [comment]
bruh
