### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by frappepancake** [PigeonVideo/PigeonVideo.github.io#28]
hello. I would like to join pigeon video please. my friend told me about it and it sounds cool 😎

**Comment by frappepancake** [comment]
I know fortran and lisp and html5 and CSS3

**Comment by LankyBox01** [comment]
Hi, those are launguages..?
Anyways, are you over 13?

**Comment by frappepancake** [comment]
yes, those are languages.
Yes i am over 13.

**Comment by LankyBox01** [comment]
Well, i am not sure how those launguages can help us.
Do you know more well-known launguages like html or css?

**Comment by frappepancake** [comment]
I have a question. why did you put your birthday in https://github.com/PigeonVideo/PigeonVideo.github.io/blob/master/Security-Tips.md?

"Your birth date would be a bad password, for example "210410". "

isn't 210410 April 21, 2010?

**Comment by LankyBox01** [comment]
That is not my birthday, i was actually born sometime else.
I am over 13, if i was born in 2010 i would be 10 right now XD

But i just entered a random date

**Comment by frappepancake** [comment]
I also know HTML, CSS, JavaScript, and how to bundle SCSS (fancier CSS) using webpack.

**Comment by LankyBox01** [comment]
Great, who told you about this website?

**Comment by frappepancake** [comment]
m4sugar

**Comment by LankyBox01** [comment]
Cool, glitch username?

**Comment by frappepancake** [comment]
https://support.glitch.com/u/frappepancake/summary

**Comment by frappepancake** [comment]
I made one

**Comment by LankyBox01** [comment]
Yea.. it is

**Comment by LankyBox01** [comment]
Oh cool

**Comment by LankyBox01** [comment]
The ban wasn't really fair.
I just invited 3-4 random people in a DM chat about pigeonvideo, and then it got more popular, lots of people wanted me to invite them to the group chat, and the admins tought i was inviting them "randomly".

Sure, ask them to unban me, i bet it'll work

**Comment by aboutDavid** [comment]
The DM also got locked
https://i.imgur.com/TdaTtSr.png

**Comment by frappepancake** [comment]
who locked it?

**Comment by aboutDavid** [comment]
The moderation bot because it reached more than 500 post.

**Comment by LankyBox01** [comment]
Oh, so thats what happened!

**Comment by aboutDavid** [comment]
Yeah, I wanted to make it like a surprise so you would laugh

**Comment by LankyBox01** [comment]
WHY THE NUGGETS WOULD THAT BE FUNNY!?!
I mean.. yeah it is

**Comment by frappepancake** [comment]
@LankyBox01 @themagiclavalamp am I accepted?
