### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#4]
So, we only get 500MB in this **Entire Repository!**
That would be a problem, you see:

One normal video would be 5-10 Minutes
Which is aproximately 7-12 MB

500:12=41.6
500:7=71.4

That would be a problem, since we would have a video limit. Unless we use a different server.
What suggestions do you have?

**Comment by LankyBox01** [comment]
We should probably use a CDN server..

**Comment by aboutDavid** [comment]
I could try to setup a CDN

**Comment by LankyBox01** [comment]
@aboutDavid Sure, but there would be a few problems with that. The upload system that 17lwinn made?

**Comment by aboutDavid** [comment]
You just push the videos to the CDN.

**Comment by aboutDavid** [comment]
Put this into the to-do
https://github.com/PigeonVideo/PigeonVideo.github.io/projects/1#card-46317865

**Comment by aboutDavid** [comment]
Could we use https://youphp.tube/ ?

**Comment by LankyBox01** [comment]
It's too simple, but i don't think a small try would hurt!

**Comment by aboutDavid** [comment]
Where should it be hosted?

**Comment by LankyBox01** [comment]
Idk register a dot.cf domain or something

**Comment by aboutDavid** [comment]
https://byet.host/free-hosting
They have unlimited storage with free file hosting

**Comment by LankyBox01** [comment]
Oh cool. Do it

**Comment by aboutDavid** [comment]
Ok

**Comment by 17lwinn** [comment]
okay, we might need an cron job or something

**Comment by LankyBox01** [comment]
Set. Up. A. CDN.

**Comment by 17lwinn** [comment]
sigh. fine
