### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#6]
So i watched [REDACTED]'s video about how the world's copyright system is broken, and i am a little bit worried.
How could we defend ourselves from copyright?? Do we like.. have to be non-profit or something?

**Comment by aboutDavid** [comment]
I believe that even non-profits can get copyright claimed. You could have an email for DMCA requests.

**Comment by LankyBox01** [comment]
Ok.. we'll solve that later
