### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by LankyBox01** [PigeonVideo/PigeonVideo.github.io#7]
Hey guys! I have licensed the PigeonVideo Logo!
It is now licensed under CC BY SA 4.0 lol

**Comment by aboutDavid** [comment]
> Hey guys! I have copyrighted the PigeonVideo Logo!
> Since i am in europe, i didn't have to pay or anything.
> 
> So now, YOU're not allowed to use it without my permission XD

So, where did the logo come from? Did you make it?

**Comment by LankyBox01** [comment]
Yes, i fully made it and i 100% own it

**Comment by 17lwinn** [comment]
If you have copyrighted it, we'll take action.

We don't even have a logo yet!

**Comment by LankyBox01** [comment]
Look at /img/PigeonVideo_Logo.png and you'll see the logo there

**Comment by aboutDavid** [comment]
There is no such thing as "international copyright".

**Comment by LankyBox01** [comment]
I didn't say "international copyright"

**Comment by 17lwinn** [comment]
Not that I know of, he can do DMCA...

**Comment by LankyBox01** [comment]
When you publish something in europe, it is already protected by copyrighht

**Comment by 17lwinn** [comment]
When you put a license on something, it's protected by copyright

**Comment by 17lwinn** [comment]
And, if the software and name are licensed- you have no right to change it.

**Comment by aboutDavid** [comment]
> When you put a license on something, it's protected by copyright

I'm just saying, it does not work in every country.

**Comment by LankyBox01** [comment]
https://www.google.com/amp/s/europa.eu/youreurope/business/running-business/intellectual-property/copyright/indexamp_en.htm

**Comment by 17lwinn** [comment]
good grief... we won't get it back for 70 years after this user has died

**Comment by LankyBox01** [comment]
Lol you're allowed to use it tho
If you want a license, i'll license it then

**Comment by LankyBox01** [comment]
Hey, my glitch account was suspended until octomber 5th

**Comment by aboutDavid** [comment]
Don't forget, [fair use](http://en.wikipedia.org/wiki/Fair_use) (or your country's equivalent) still applies.
